FROM golang:alpine
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN apk add git
RUN go mod tidy
RUN go build -o main .
ENV ENV prod
ARG TWITTER_KEY
ENV TWITTER_KEY=$TWITTER_KEY
ARG TWITTER_SECRET
ENV TWITTER_SECRET=$TWITTER_SECRET
EXPOSE 8080

ENTRYPOINT ["/app/main"]